Repository canonical/netplan, pull requests merged in 2024-08, with the labels that each got.

#494 Add netplan try to netplan tutorial
  doc/netplan-tutorial.md
Labels: community, documentation

#500 Update the docs checks runner to ubuntu-latest
  .github/workflows/automatic-doc-checks.yml
Labels: bug, documentation

#499 Add spelling exceptions
  doc/.custom_wordlist.txt
Labels: enhancement, documentation

#495 netplan ignores NetworkManager ipv4.route-metric (LP: #2076172)
  src/nm.c
  tests/parser/test_keyfile.py
Labels: community

#497 Change default umask when creating dirctories (LP: #2076319)
  src/util.c
Labels: community, Canonical

#509 tests: ethernets: Add ipv6-address-generation integration tests
  tests/integration/base.py
  tests/integration/ethernets.py
Labels: community
