Repository canonical/netplan, pull requests merged in 2024-06, with the labels that each got.

#473 migrate: support aliases
  netplan_cli/cli/commands/migrate.py
  tests/cli_legacy.py
Labels: community

#457 added guide for contributing to the netplan documentation
  README.md
  doc/contribute-docs.md
  doc/netplan-yaml.md
Labels: community, documentation

#461 feat(networkd): add ipv6 ra overrides (LP: #1973222)
  doc/netplan-yaml.md
  src/abi.h
  src/netplan.c
  src/networkd.c
  src/parse.c
  src/types.c
  tests/generator/test_ra_overrides.py
Labels: schema change, schema ok, community

#475 Create single-nic-vm-host.md
  doc/howto.md
  doc/single-nic-vm-host.md
Labels: community, documentation, Canonical

#476 Create single-nic-vm-host-with-vlans.md
  doc/howto.md
  doc/single-nic-vm-host-with-vlans.md
Labels: community, documentation, Canonical

#477 Create multi-nic-vm-host-with-bonds-and-vlans.md
  doc/howto.md
  doc/multi-nic-vm-host-with-bonds-and-vlans.md
Labels: community, documentation, Canonical

#449 apply: make sure that networkd is restarted when needed
  netplan_cli/cli/commands/apply.py
Labels: community, Canonical

#483 bullet point removal
  doc/netplan-generate.md
Labels: community, documentation
